### ISSUE TITLE
Failed to load the require package

### ISSUE THREAD

**Issue by journeymenmomo** [craig-o/atom-require#23]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.22.0 x64
**Electron**: 1.6.15
**OS**: Unknown Windows version
**Thrown From**: [require](https://github.com/craig-o/atom-require) package 0.1.0

### Stack Trace

Failed to load the require package

```
At atom.project.getPath is not a function

TypeError: atom.project.getPath is not a function
    at /packages/require/views/require-view.js:3:32)
    at /packages/require/views/require-view.js:71:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.22.0/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.22.0/resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (~/AppData/Local/atom/app-1.22.0/resources/app/src/native-compile-cache.js:66:33)
    at /packages/require/index.js:2:19)
    at /packages/require/index.js:21:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.22.0/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.22.0/resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (internal/module.js:20:19)
    at customRequire (~/AppData/Local/atom/app-1.22.0/resources/app/static/<embedded>:96:26)
    at Package.module.exports.Package.requireMainModule (~/AppData/Local/atom/app-1.22.0/resources/app/src/package.js:903:35)
    at ~/AppData/Local/atom/app-1.22.0/resources/app/src/package.js:158:34
    at Package.module.exports.Package.measure (~/AppData/Local/atom/app-1.22.0/resources/app/src/package.js:99:21)
    at Package.module.exports.Package.load (~/AppData/Local/atom/app-1.22.0/resources/app/src/package.js:144:18)
    at PackageManager.loadAvailablePackage (~/AppData/Local/atom/app-1.22.0/resources/app/src/package-manager.js:617:16)
    at config.transact (~/AppData/Local/atom/app-1.22.0/resources/app/src/package-manager.js:530:20)
    at Config.module.exports.Config.transact (~/AppData/Local/atom/app-1.22.0/resources/app/src/config.js:342:22)
    at PackageManager.loadPackages (~/AppData/Local/atom/app-1.22.0/resources/app/src/package-manager.js:528:23)
    at ~/AppData/Local/atom/app-1.22.0/resources/app/src/atom-environment.js:821:34
```

### Commands

```
```

### Non-Core Packages

```
atom-runner 2.7.1 
markdown-preview-plus 2.4.16 
node-requirer 0.1.12 
require 0.1.0 
```

**Comment by journeymenmomo** [comment]
wrong？
